const KEY='pcm_preventiva_v4';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const clone=o=>JSON.parse(JSON.stringify(o));
const today=()=>new Date().toISOString().slice(0,10);const fmt=s=>{if(!s)return'—';const [y,m,d]=s.split('-');return`${d}/${m}/${y}`};const parse=s=>new Date(s+'T12:00:00');const addDays=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+Number(n));return d.toISOString().slice(0,10)};const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const uid=()=>crypto?.randomUUID?.()||'id-'+Date.now()+Math.random();
function normalizePlan(p){return{...p,disciplina:p.disciplina||guessDiscipline(p.plano,p.descricao),duracaoEstimada:Number(p.duracaoEstimada||1),equipe:Number(p.equipe||1),materiais:p.materiais||'',checklist:Array.isArray(p.checklist)?p.checklist:defaultChecklist(p),criticidade:p.criticidade||'Média',ativo:p.ativo!==false}}
function guessDiscipline(a='',b=''){const t=(a+' '+b).toLowerCase();if(/el[eé]tric|motor|painel|sensor|cabo/.test(t))return'Elétrica';if(/lubri|graxa|óleo|oleo/.test(t))return'Lubrificação';if(/clp|autom|i\/o|software|inversor/.test(t))return'Automação';return'Mecânica'}
function defaultChecklist(p){const n=(p.plano||'').toLowerCase();if(/lubri/.test(n))return['Verificar condição e ponto de lubrificação','Limpar ponto antes da aplicação','Aplicar lubrificante conforme especificação','Registrar anomalias'];return['Inspecionar condição geral do equipamento','Verificar fixações, folgas e ruídos anormais','Verificar componentes de desgaste','Limpar área de intervenção','Registrar anomalias encontradas']}
function seedState(){return{version:2,plans:clone(window.SEED_PLANS||[]).map(normalizePlan),orders:[],executions:[],updatedAt:new Date().toISOString()}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d?.plans)return migrate(d)}catch{}return seedState()}
function migrate(d){d.version=2;d.plans=(d.plans||[]).map(normalizePlan);d.orders=d.orders||[];d.executions=d.executions||[];return d}let state=load();
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}function getPlan(u){return state.plans.find(p=>p.uid===u)}
function lastDone(u){return state.executions.filter(e=>e.planUid===u&&e.doneDate).sort((a,b)=>b.doneDate.localeCompare(a.doneDate))[0]}
function dueDate(p){const l=lastDone(p.uid);const ref=l?.doneDate||p.dataBase||today();return addDays(ref,Math.max(1,+p.periodicidade||30))}
function isLate(p){return p.ativo&&dueDate(p)<today()}
function schedule(days=90){const end=addDays(today(),days),rows=[];state.plans.filter(p=>p.ativo).forEach(p=>{let d=dueDate(p),f=Math.max(1,+p.periodicidade||30),g=0;while(d<today()&&g++<1000){rows.push({date:d,plan:p,late:true});d=addDays(d,f)}while(d<=end&&g++<1300){rows.push({date:d,plan:p,late:false});d=addDays(d,f)}});return rows.sort((a,b)=>a.date.localeCompare(b.date))}
function assetList(){const m=new Map();state.plans.forEach(p=>{if(!m.has(p.tag))m.set(p.tag,{tag:p.tag,descricao:p.descricao,setor:p.setor,plans:[]});m.get(p.tag).plans.push(p)});return[...m.values()]}
const critRank={Crítica:4,Alta:3,Média:2,Baixa:1};function worstCrit(plans){return[...plans].sort((a,b)=>(critRank[b.criticidade]||0)-(critRank[a.criticidade]||0))[0]?.criticidade||'—'}
function nextPlanId(){const n=state.plans.map(p=>+(String(p.id).match(/\d+/)?.[0]||0));return'PLN-'+String(Math.max(0,...n)+1).padStart(3,'0')}function nextOrder(){const n=state.orders.map(o=>+(String(o.number).match(/\d+/)?.[0]||0));return'SS-'+String(Math.max(0,...n)+1).padStart(5,'0')}
function badge(v){let c='';if(['Vencido','Crítica'].includes(v))c='red';else if(['Alta','Aguardando material'].includes(v))c='amber';else if(['Em execução'].includes(v))c='blue';else if(['Cancelada','Inativo'].includes(v))c='gray';return`<span class="badge ${c}">${esc(v)}</span>`}
function renderDashboard(){const active=state.plans.filter(p=>p.ativo),assets=assetList(),sch=schedule(30),late=active.filter(isLate),open=state.orders.filter(o=>!['Concluída','Cancelada'].includes(o.status)),done=state.executions.filter(e=>e.doneDate),ontime=done.filter(e=>e.doneDate<=e.plannedDate);$('#kpiPlans').textContent=planGroups(active).length;$('#kpiAssets').textContent=assets.length;$('#kpi30').textContent=sch.filter(x=>!x.late).length;$('#kpiLate').textContent=late.length;$('#kpiOpenOrders').textContent=open.length;$('#kpiCompliance').textContent=done.length?Math.round(ontime.length/done.length*100)+'%':'—';
const upcoming=schedule(30).slice(0,10);$('#upcomingList').innerHTML=upcoming.length?upcoming.map(x=>`<div class="timeline-item"><div class="datebox">${fmt(x.date)}</div><div><strong>${esc(x.plan.plano)}</strong><small>${esc(x.plan.tag)} · ${esc(x.plan.setor)} · ${esc(x.plan.responsavel||'Sem responsável')}</small></div>${badge(x.late?'Vencido':x.plan.criticidade)}</div>`).join(''):'<div class="empty">Sem programação.</div>';
const pc={Crítica:0,Alta:0,Média:0,Baixa:0};late.forEach(p=>pc[p.criticidade]=(pc[p.criticidade]||0)+1);$('#priorityDonut').innerHTML=Object.entries(pc).map(([k,v])=>`<div class="priority-card"><span>${k}</span><strong>${v}</strong></div>`).join('');
const counts={};active.forEach(p=>counts[p.setor||'Sem setor']=(counts[p.setor||'Sem setor']||0)+1);renderBars('#sectorBars',counts);
const alerts=[];if(late.length)alerts.push(`<div class="alert"><strong>${late.length} preventiva(s) vencida(s)</strong><small>Priorize a regularização do backlog.</small></div>`);if(open.filter(o=>o.status==='Aguardando material').length)alerts.push(`<div class="alert"><strong>${open.filter(o=>o.status==='Aguardando material').length} SS aguardando material</strong><small>Verifique compras e disponibilidade de peças.</small></div>`);const criticalLate=late.filter(p=>p.criticidade==='Crítica').length;if(criticalLate)alerts.push(`<div class="alert"><strong>${criticalLate} plano(s) crítico(s) vencido(s)</strong><small>Requer ação prioritária.</small></div>`);if(!alerts.length)alerts.push('<div class="alert"><strong>Sem alertas críticos</strong><small>A programação está sob controle.</small></div>');$('#alerts').innerHTML=alerts.join('')}
function renderBars(sel,obj){const arr=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,12),mx=Math.max(1,...arr.map(x=>x[1]));$(sel).innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-row"><span title="${esc(k)}">${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/mx*100}%"></div></div><strong>${v}</strong></div>`).join(''):'<div class="empty">Sem dados.</div>'}
function fillSectors(){const sectors=[...new Set(state.plans.map(p=>p.setor).filter(Boolean))].sort();for(const id of ['assetSector','planSector']){const el=$(id.startsWith('#')?id:'#'+id),cur=el.value;el.innerHTML='<option value="">Todos os setores</option>'+sectors.map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}}
function renderAssets(){const q=$('#assetSearch').value.toLowerCase(),sec=$('#assetSector').value;const rows=assetList().filter(a=>(!q||[a.tag,a.descricao,a.setor].join(' ').toLowerCase().includes(q))&&(!sec||a.setor===sec));$('#assetsBody').innerHTML=rows.length?rows.map(a=>{const act=a.plans.filter(p=>p.ativo);const next=act.map(p=>({p,d:dueDate(p)})).sort((x,y)=>x.d.localeCompare(y.d))[0];return`<tr><td><strong>${esc(a.tag)}</strong></td><td>${esc(a.descricao||'—')}</td><td>${esc(a.setor||'—')}</td><td>${a.plans.length}</td><td>${badge(worstCrit(a.plans))}</td><td>${next?fmt(next.d):'—'}</td><td>${next?badge(next.d<today()?'Vencido':'Em dia'):'—'}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Nenhum equipamento encontrado.</td></tr>'}
function planGroupKey(p){return (p.plano||p.id||'SEM PLANO').trim().toLocaleUpperCase('pt-BR')}
function planGroups(plans=state.plans){const m=new Map();plans.forEach(p=>{const k=planGroupKey(p);if(!m.has(k))m.set(k,{key:k,name:p.plano||p.id,ids:new Set(),tags:new Set(),items:[],periods:new Set(),sectors:new Set(),owners:new Set()});const g=m.get(k);g.items.push(p);g.ids.add(p.id);g.tags.add(p.tag);g.periods.add(+p.periodicidade||30);if(p.setor)g.sectors.add(p.setor);if(p.responsavel)g.owners.add(p.responsavel)});return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
const expandedPlanGroups=new Set();
window.togglePlanGroup=k=>{expandedPlanGroups.has(k)?expandedPlanGroups.delete(k):expandedPlanGroups.add(k);renderPlans()};
function renderPlans(){const q=$('#planSearch').value.toLowerCase(),sec=$('#planSector').value,cr=$('#planCriticality').value,st=$('#planStatus').value;const filtered=state.plans.filter(p=>(!q||[p.id,p.plano,p.tag,p.descricao,p.setor,p.responsavel].join(' ').toLowerCase().includes(q))&&(!sec||p.setor===sec)&&(!cr||p.criticidade===cr)&&(st===''||String(!!p.ativo)===st));const groups=planGroups(filtered);$('#plansBody').innerHTML=groups.length?groups.map(g=>{const expanded=expandedPlanGroups.has(g.key),active=g.items.filter(p=>p.ativo),late=active.filter(isLate).length,next=active.map(p=>dueDate(p)).sort()[0],period=[...g.periods].sort((a,b)=>a-b).map(x=>x+'d').join(', '),ids=[...g.ids].join(', ');const head=`<tr class="plan-master-row"><td><button class="group-toggle" onclick='togglePlanGroup(${JSON.stringify(g.key)})'>${expanded?'−':'+'}</button> <strong>${esc(ids)}</strong></td><td><strong>${esc(g.name)}</strong><small class="subline">${g.items.length} cadastro(s) · ${g.tags.size} TAG(s)</small></td><td><span class="tag-count">${g.tags.size} TAGs</span></td><td>${esc([...g.sectors].join(', ')||'—')}</td><td>—</td><td>${esc(period)}</td><td>${esc([...g.owners].slice(0,3).join(', ')||'—')}</td><td>${badge(worstCrit(g.items))}</td><td>${next?fmt(next):'—'}${late?`<small class="subline danger-text">${late} vencida(s)</small>`:''}</td><td><button class="mini" onclick='togglePlanGroup(${JSON.stringify(g.key)})'>${expanded?'Ocultar TAGs':'Ver TAGs'}</button></td></tr>`;const children=expanded?g.items.sort((a,b)=>a.tag.localeCompare(b.tag,'pt-BR')).map(p=>`<tr class="plan-tag-row"><td></td><td><span class="indent">↳ ${esc(p.descricao||p.plano)}</span></td><td><strong>${esc(p.tag)}</strong></td><td>${esc(p.setor||'—')}</td><td>${esc(p.disciplina||'—')}</td><td>${p.periodicidade} dias</td><td>${esc(p.responsavel||'—')}</td><td>${badge(p.criticidade)}</td><td><strong>${fmt(dueDate(p))}</strong><small class="subline">Última: ${fmt(lastReference(p))}</small></td><td><div class="actions"><button class="mini" onclick="openExecute('${p.uid}','${dueDate(p)}')">Baixar</button><button class="mini" onclick="editPlan('${p.uid}')">Editar</button><button class="mini" onclick="newOrderForPlan('${p.uid}')">SS</button></div></td></tr>`).join(''):'';return head+children}).join(''):'<tr><td colspan="10" class="empty">Nenhum plano encontrado.</td></tr>'}
function renderAgenda(){const q=$('#agendaSearch').value.toLowerCase(),sit=$('#agendaSituation').value,days=+$(`#agendaDays`).value;const rows=schedule(days).filter(x=>!q||[x.plan.id,x.plan.plano,x.plan.tag,x.plan.setor].join(' ').toLowerCase().includes(q)).filter(x=>!sit||(x.late?'Vencido':'Planejado')===sit);$('#agendaBody').innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${fmt(x.date)}</strong></td><td>${badge(x.late?'Vencido':'Planejado')}</td><td>${esc(x.plan.id)}</td><td>${esc(x.plan.plano)}</td><td>${esc(x.plan.tag)}</td><td>${esc(x.plan.setor)}</td><td>${badge(x.plan.criticidade)}</td><td>${esc(x.plan.responsavel||'—')}</td><td><button class="mini" onclick="openExecute('${x.plan.uid}','${x.date}')">Executar</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">Nenhuma atividade encontrada.</td></tr>'}
function renderOrders(){const q=$('#orderSearch').value.toLowerCase(),st=$('#orderStatus').value;const rows=[...state.orders].sort((a,b)=>b.openDate.localeCompare(a.openDate)).filter(o=>(!q||[o.number,o.description,o.tag,o.owner,getPlan(o.planUid)?.plano].join(' ').toLowerCase().includes(q))&&(!st||o.status===st));$('#ordersBody').innerHTML=rows.length?rows.map(o=>{const p=getPlan(o.planUid);return`<tr><td><strong>${esc(o.number)}</strong></td><td>${esc(p?.plano||o.description||'Serviço avulso')}</td><td>${esc(o.tag||p?.tag||'—')}</td><td>${fmt(o.openDate)}</td><td>${fmt(o.plannedDate)}</td><td>${badge(o.priority)}</td><td>${esc(o.owner||'—')}</td><td>${badge(o.status)}</td><td><div class="actions"><button class="mini" onclick="editOrder('${o.uid}')">Editar</button>${o.status!=='Concluída'?`<button class="mini" onclick="executeOrder('${o.uid}')">Baixar</button>`:''}</div></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma SS / ordem cadastrada.</td></tr>'}
function renderHistory(){const q=$('#historySearch').value.toLowerCase(),y=$('#historyYear').value;const rows=[...state.executions].sort((a,b)=>b.doneDate.localeCompare(a.doneDate)).filter(e=>{const p=getPlan(e.planUid)||{};return(!q||[p.plano,p.tag,e.orderNumber,e.owner,e.notes].join(' ').toLowerCase().includes(q))&&(!y||e.doneDate?.startsWith(y))});$('#historyBody').innerHTML=rows.length?rows.map(e=>{const p=getPlan(e.planUid)||{};return`<tr><td>${fmt(e.plannedDate)}</td><td>${fmt(e.doneDate)}</td><td>${esc(p.plano||'Plano removido')}</td><td>${esc(p.tag||'—')}</td><td>${esc(e.orderNumber||'—')}</td><td>${esc(e.owner||'—')}</td><td>${e.hours||0} h</td><td>${badge(e.result||'Concluído')}</td><td>${esc(e.notes||'—')}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma execução registrada.</td></tr>';const yrs=[...new Set(state.executions.map(e=>e.doneDate?.slice(0,4)).filter(Boolean))].sort().reverse(),cur=$('#historyYear').value;$('#historyYear').innerHTML='<option value="">Todos os anos</option>'+yrs.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}
function renderIndicators(){const done=state.executions.filter(e=>e.doneDate),ont=done.filter(e=>e.doneDate<=e.plannedDate),late=done.filter(e=>e.doneDate>e.plannedDate),hours=done.reduce((s,e)=>s+(+e.hours||0),0);$('#indDone').textContent=done.length;$('#indOntime').textContent=ont.length;$('#indLate').textContent=late.length;$('#indHours').textContent=hours.toFixed(1)+'h';const sectors={};done.forEach(e=>{const p=getPlan(e.planUid),s=p?.setor||'Sem setor';sectors[s]??={t:0,o:0};sectors[s].t++;if(e.doneDate<=e.plannedDate)sectors[s].o++});const rates={};Object.entries(sectors).forEach(([k,v])=>rates[k]=Math.round(v.o/v.t*100));renderBars('#complianceBars',rates);const months=[];let d=new Date();for(let i=11;i>=0;i--){const x=new Date(d.getFullYear(),d.getMonth()-i,1),key=x.toISOString().slice(0,7),lab=String(x.getMonth()+1).padStart(2,'0')+'/'+String(x.getFullYear()).slice(2);months.push({key,lab,v:done.filter(e=>e.doneDate?.startsWith(key)).length})}const mx=Math.max(1,...months.map(m=>m.v));$('#monthBars').innerHTML=months.map(m=>`<div class="month-col"><strong>${m.v}</strong><div class="col" style="height:${Math.max(3,m.v/mx*180)}px"></div><small>${m.lab}</small></div>`).join('');const adh=done.length?Math.round(ont.length/done.length*100):0,avg=done.length?hours/done.length:0;$('#managementSummary').innerHTML=`<div class="summary-item"><span>Aderência global</span><strong>${adh}%</strong></div><div class="summary-item"><span>Duração média</span><strong>${avg.toFixed(1)} h</strong></div><div class="summary-item"><span>Backlog vencido</span><strong>${state.plans.filter(isLate).length}</strong></div><div class="summary-item"><span>Ordens abertas</span><strong>${state.orders.filter(o=>!['Concluída','Cancelada'].includes(o.status)).length}</strong></div>`}
function renderAll(){fillSectors();$('#baseCount').textContent=`${planGroups(state.plans).length} planos · ${state.plans.length} vínculos`;renderDashboard();renderAssets();renderPlans();renderAgenda();renderOrders();renderHistory();renderIndicators();fillOrderPlans();if(typeof renderGantt==='function')renderGantt()}
const titles={dashboard:['Dashboard','Visão geral da programação preventiva'],equipamentos:['Equipamentos','TAGs e cobertura dos planos'],planos:['Planos de manutenção','Cadastro técnico e periodicidades'],agenda:['Programação preventiva','Calendário e backlog das atividades'],mapa:['Mapa 52 semanas','Cronograma anual calculado por datas reais'],gantt:['Cronograma 52 semanas','Planejado x realizado por plano e TAG'],ordens:['SS / Ordens','Controle de serviços e andamento'],execucoes:['Histórico de execuções','Rastreabilidade das manutenções realizadas'],indicadores:['Indicadores','Aderência, backlog e esforço preventivo'],usuarios:['Usuários','Perfis, acesso e rastreabilidade'],backup:['Dados / Backup','Exportação, importação e configurações']};function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1]}
function openPlan(p){$('#planForm').reset();$('#pUid').value=p?.uid||'';$('#pId').value=p?.id||nextPlanId();$('#pTag').value=p?.tag||'';$('#pName').value=p?.plano||'';$('#pDescription').value=p?.descricao||'';$('#pSector').value=p?.setor||'';$('#pOwner').value=p?.responsavel||'';$('#pDiscipline').value=p?.disciplina||'Mecânica';$('#pCriticality').value=p?.criticidade||'Média';$('#pFrequency').value=p?.periodicidade||30;$('#pBaseDate').value=p?.dataBase||today();$('#pDuration').value=p?.duracaoEstimada||1;$('#pCrew').value=p?.equipe||1;$('#pMaterials').value=p?.materiais||'';$('#pChecklist').value=(p?.checklist||[]).join('\n');$('#pActive').checked=p?p.ativo!==false:true;$('#planDialogTitle').textContent=p?'Editar plano':'Novo plano';$('#planDialog').showModal()}window.editPlan=u=>openPlan(getPlan(u));
function fillOrderPlans(){const cur=$('#oPlan').value;$('#oPlan').innerHTML='<option value="">Serviço avulso</option>'+state.plans.map(p=>`<option value="${p.uid}" ${p.uid===cur?'selected':''}>${esc(p.id)} · ${esc(p.tag)} · ${esc(p.plano)}</option>`).join('')}
function openOrder(o,planUid){$('#orderForm').reset();fillOrderPlans();$('#oUid').value=o?.uid||'';$('#oNumber').value=o?.number||nextOrder();$('#oPlan').value=o?.planUid||planUid||'';const p=getPlan($('#oPlan').value);$('#oTag').value=o?.tag||p?.tag||'';$('#oStatus').value=o?.status||'Aberta';$('#oOpenDate').value=o?.openDate||today();$('#oPlannedDate').value=o?.plannedDate||p?dueDate(p):today();$('#oPriority').value=o?.priority||p?.criticidade||'Média';$('#oOwner').value=o?.owner||p?.responsavel||'';$('#oDescription').value=o?.description||p?.plano||'';$('#oNotes').value=o?.notes||'';$('#orderDialogTitle').textContent=o?'Editar SS / Ordem':'Nova SS / Ordem';$('#orderDialog').showModal()}window.editOrder=u=>openOrder(state.orders.find(o=>o.uid===u));window.newOrderForPlan=u=>openOrder(null,u);
function openExecute(planUid,plannedDate,orderUid=''){const p=getPlan(planUid),o=state.orders.find(x=>x.uid===orderUid);if(!p&&o?.planUid)planUid=o.planUid;const pl=getPlan(planUid);if(!pl){alert('É necessário vincular a ordem a um plano para baixar nesta tela.');return}$('#executeForm').reset();$('#ePlanUid').value=pl.uid;$('#eOrderUid').value=orderUid||'';$('#ePlannedDate').value=plannedDate||o?.plannedDate||dueDate(pl);$('#eDoneDate').value=today();$('#eOrderNumber').value=o?.number||'';$('#eOwner').value=o?.owner||pl.responsavel||'';$('#eHours').value=pl.duracaoEstimada||1;$('#execPlanInfo').innerHTML=`<strong>${esc(pl.id)} · ${esc(pl.plano)}</strong><br>${esc(pl.tag)} · ${esc(pl.setor)} · ${pl.periodicidade} dias`;$('#execChecklist').innerHTML=(pl.checklist||[]).map((c,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"> <span>${esc(c)}</span></label>`).join('');$('#executeDialog').showModal()}window.openExecute=openExecute;window.executeOrder=u=>{const o=state.orders.find(x=>x.uid===u);if(!o)return;openExecute(o.planUid,o.plannedDate,o.uid)};
$('#planForm').onsubmit=e=>{e.preventDefault();const d=normalizePlan({uid:$('#pUid').value||uid(),id:$('#pId').value.trim(),tag:$('#pTag').value.trim(),plano:$('#pName').value.trim(),descricao:$('#pDescription').value.trim(),setor:$('#pSector').value.trim(),responsavel:$('#pOwner').value.trim(),disciplina:$('#pDiscipline').value,criticidade:$('#pCriticality').value,periodicidade:+$('#pFrequency').value,dataBase:$('#pBaseDate').value,duracaoEstimada:+$('#pDuration').value,equipe:+$('#pCrew').value,materiais:$('#pMaterials').value.trim(),checklist:$('#pChecklist').value.split('\n').map(x=>x.trim()).filter(Boolean),ativo:$('#pActive').checked});const i=state.plans.findIndex(p=>p.uid===d.uid);if(i>=0)state.plans[i]=d;else state.plans.unshift(d);$('#planDialog').close();save();toast(i>=0?'Plano atualizado':'Plano cadastrado')};
$('#orderForm').onsubmit=e=>{e.preventDefault();const d={uid:$('#oUid').value||uid(),number:$('#oNumber').value.trim(),planUid:$('#oPlan').value,tag:$('#oTag').value.trim(),status:$('#oStatus').value,openDate:$('#oOpenDate').value,plannedDate:$('#oPlannedDate').value,priority:$('#oPriority').value,owner:$('#oOwner').value.trim()||currentUserName(),createdBy:currentUserName(),description:$('#oDescription').value.trim(),notes:$('#oNotes').value.trim(),updatedAt:new Date().toISOString()};const i=state.orders.findIndex(o=>o.uid===d.uid);if(i>=0)state.orders[i]=d;else state.orders.unshift(d);$('#orderDialog').close();save();toast(i>=0?'SS atualizada':'SS cadastrada')};
$('#executeForm').onsubmit=e=>{e.preventDefault();const checked=[...document.querySelectorAll('[data-check]')].map((x,i)=>({index:i,done:x.checked}));const ex={uid:uid(),planUid:$('#ePlanUid').value,orderUid:$('#eOrderUid').value,plannedDate:$('#ePlannedDate').value,doneDate:$('#eDoneDate').value,orderNumber:$('#eOrderNumber').value.trim(),owner:$('#eOwner').value.trim()||currentUserName(),createdBy:currentUserName(),hours:+$('#eHours').value,result:$('#eResult').value,materials:$('#eMaterials').value.trim(),notes:$('#eNotes').value.trim(),checklist:checked,createdAt:new Date().toISOString()};state.executions.push(ex);if(ex.orderUid){const o=state.orders.find(o=>o.uid===ex.orderUid);if(o)o.status='Concluída'}$('#executeDialog').close();save();toast('Execução registrada')};
$('#oPlan').onchange=()=>{const p=getPlan($('#oPlan').value);if(p){$('#oTag').value=p.tag;$('#oPlannedDate').value=dueDate(p);$('#oPriority').value=p.criticidade;$('#oOwner').value=p.responsavel||'';$('#oDescription').value=p.plano}};
function exportJson(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`pcm-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}function exportCsv(){const cols=['ID','Plano','TAG','Descrição','Setor','Disciplina','Periodicidade','Responsável','Criticidade','Data-base','Ativo'];const lines=[cols.join(';'),...state.plans.map(p=>[p.id,p.plano,p.tag,p.descricao,p.setor,p.disciplina,p.periodicidade,p.responsavel,p.criticidade,p.dataBase,p.ativo?'Sim':'Não'].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';'))];const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`planos-preventiva-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>switchView(b.dataset.goto));$('#btnNewPlan').onclick=()=>openPlan();$('#btnQuickOrder').onclick=()=>openOrder();$('#btnNewOrder2').onclick=()=>openOrder();$$('.close-plan').forEach(b=>b.onclick=()=>$('#planDialog').close());$$('.close-order').forEach(b=>b.onclick=()=>$('#orderDialog').close());$$('.close-exec').forEach(b=>b.onclick=()=>$('#executeDialog').close());
['assetSearch','planSearch','agendaSearch','orderSearch','historySearch'].forEach(id=>$('#'+id).oninput=renderAll);['assetSector','planSector','planCriticality','planStatus','agendaDays','agendaSituation','orderStatus','historyYear'].forEach(id=>$('#'+id).onchange=renderAll);$('#exportJson').onclick=exportJson;$('#exportCsv').onclick=exportCsv;$('#importJson').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.plans))throw 0;if(confirm('Substituir a base atual por este backup?')){state=migrate(d);save();toast('Backup importado')}}catch{alert('Arquivo inválido.')}e.target.value=''};$('#resetData').onclick=()=>{if(confirm('Restaurar a base original e apagar alterações locais?')){state=seedState();save();toast('Base restaurada')}};renderAll();


/* ===== V3: LOGIN + MAPA DE 52 SEMANAS ===== */
const USER_KEY='pcm_preventiva_users_v3', SESSION_KEY='pcm_preventiva_session_v3';
const dateOnly=d=>{const x=new Date(d);x.setHours(12,0,0,0);return x};
const isoDate=d=>{const x=new Date(d);const y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),day=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
function mondayOf(s=today()){const d=parse(s),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return isoDate(d)}
function daysBetween(a,b){return Math.floor((parse(b)-parse(a))/86400000)}
function currentUserName(){return loadUsers().find(u=>u.id===localStorage.getItem(SESSION_KEY))?.name||''}
function defaultUsers(){return[{id:'usr-admin',name:'Administrador PCM',username:'admin',password:'admin123',role:'Admin',active:true,lastAccess:''}]}
function loadUsers(){try{const x=JSON.parse(localStorage.getItem(USER_KEY));if(Array.isArray(x)&&x.length)return x}catch{}const u=defaultUsers();localStorage.setItem(USER_KEY,JSON.stringify(u));return u}
function saveUsers(u){localStorage.setItem(USER_KEY,JSON.stringify(u));renderUsers()}
function sessionUser(){const id=localStorage.getItem(SESSION_KEY);return loadUsers().find(u=>u.id===id&&u.active)||null}
function showLogin(){const u=sessionUser();$('#loginScreen').classList.toggle('hidden',!!u);if(u){$('#sessionUser').textContent=`${u.name} · ${u.role}`;$('#headerUser').textContent=u.name;$('#currentSessionInfo').innerHTML=`<strong>${esc(u.name)}</strong><br>${esc(u.role)} · @${esc(u.username)}`;applyPermissions(u)}else{$('#sessionUser').textContent='Usuário não autenticado';$('#headerUser').textContent=''}}
function applyPermissions(u){const canManage=u.role==='Admin', canPlan=['Admin','PCM'].includes(u.role);const usersNav=document.querySelector('[data-view="usuarios"]');if(usersNav)usersNav.style.display=canManage?'':'none';$('#btnNewPlan').style.display=canPlan?'':'none';if($('#resetData'))$('#resetData').style.display=canManage?'':'none'}
$('#loginForm').onsubmit=e=>{e.preventDefault();const un=$('#loginUser').value.trim().toLowerCase(),pw=$('#loginPassword').value;const users=loadUsers(),u=users.find(x=>x.username.toLowerCase()===un&&x.password===pw&&x.active);if(!u){$('#loginError').textContent='Usuário ou senha inválidos.';return}u.lastAccess=new Date().toISOString();saveUsers(users);localStorage.setItem(SESSION_KEY,u.id);$('#loginError').textContent='';showLogin();renderAll();toast(`Bem-vindo, ${u.name}`)};
$('#btnLogout').onclick=()=>{localStorage.removeItem(SESSION_KEY);showLogin()};

function openUser(u){if(sessionUser()?.role!=='Admin')return;$('#userForm').reset();$('#uId').value=u?.id||'';$('#uName').value=u?.name||'';$('#uUsername').value=u?.username||'';$('#uPassword').value='';$('#uPassword').required=!u;$('#uRole').value=u?.role||'Executor';$('#uActive').checked=u?u.active!==false:true;$('#userDialogTitle').textContent=u?'Editar usuário':'Novo usuário';$('#userDialog').showModal()}
window.editUser=id=>openUser(loadUsers().find(u=>u.id===id));
window.toggleUser=id=>{if(sessionUser()?.role!=='Admin')return;const users=loadUsers(),u=users.find(x=>x.id===id);if(!u||u.id===sessionUser().id)return;u.active=!u.active;saveUsers(users);toast(u.active?'Usuário ativado':'Usuário desativado')};
function renderUsers(){const body=$('#usersBody');if(!body)return;const users=loadUsers();body.innerHTML=users.map(u=>`<tr><td><strong>${esc(u.name)}</strong></td><td>@${esc(u.username)}</td><td>${badge(u.role)}</td><td>${u.active?badge('Ativo'):badge('Inativo')}</td><td>${u.lastAccess?new Date(u.lastAccess).toLocaleString('pt-BR'):'—'}</td><td>${sessionUser()?.role==='Admin'?`<div class="actions"><button class="mini" onclick="editUser('${u.id}')">Editar</button>${u.id!==sessionUser()?.id?`<button class="mini" onclick="toggleUser('${u.id}')">${u.active?'Desativar':'Ativar'}</button>`:''}</div>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Sem usuários.</td></tr>'}
$('#btnNewUser').onclick=()=>openUser();$$('.close-user').forEach(b=>b.onclick=()=>$('#userDialog').close());
$('#userForm').onsubmit=e=>{e.preventDefault();const users=loadUsers(),id=$('#uId').value||uid(),username=$('#uUsername').value.trim();if(users.some(u=>u.id!==id&&u.username.toLowerCase()===username.toLowerCase())){alert('Este usuário já existe.');return}const old=users.find(u=>u.id===id),pw=$('#uPassword').value;const obj={id,name:$('#uName').value.trim(),username,role:$('#uRole').value,active:$('#uActive').checked,password:pw||old?.password||'1234',lastAccess:old?.lastAccess||''};const i=users.findIndex(u=>u.id===id);if(i>=0)users[i]=obj;else users.push(obj);saveUsers(users);$('#userDialog').close();toast(i>=0?'Usuário atualizado':'Usuário criado')};
$('#btnChangePassword').onclick=()=>{const u=sessionUser();if(!u)return;const pw=prompt('Digite a nova senha (mínimo 4 caracteres):');if(!pw)return;if(pw.length<4){alert('A senha precisa ter pelo menos 4 caracteres.');return}const users=loadUsers(),x=users.find(v=>v.id===u.id);x.password=pw;saveUsers(users);toast('Senha alterada')};

function lastReference(p){const x=lastDone(p.uid);return x?.doneDate||p.ultimaExecucaoFonte||p.dataBase||today()}
function firstDue(p){return addDays(lastReference(p),Math.max(1,+p.periodicidade||30))}
dueDate=firstDue;
function latestOverdueAndNext(p,horizonEnd){const f=Math.max(1,+p.periodicidade||30),ref=lastReference(p);let d=addDays(ref,f),lastOverdue=null,guard=0;while(d<today()&&guard++<2000){lastOverdue=d;d=addDays(d,f)}const future=[];while(d<=horizonEnd&&guard++<3000){future.push(d);d=addDays(d,f)}return{lastOverdue,future}}
function isLate(p){return p.ativo&&!!latestOverdueAndNext(p,today()).lastOverdue}
function schedule(days=90){const end=addDays(today(),days),rows=[];state.plans.filter(p=>p.ativo).forEach(p=>{const x=latestOverdueAndNext(p,end);if(x.lastOverdue)rows.push({date:x.lastOverdue,plan:p,late:true});x.future.forEach(d=>rows.push({date:d,plan:p,late:false}))});return rows.sort((a,b)=>a.date.localeCompare(b.date))}
function weekList52(){const start=mondayOf(today()),weeks=[];for(let i=0;i<52;i++){const s=addDays(start,i*7),e=addDays(s,6);weeks.push({i,start:s,end:e,label:`S${String(i+1).padStart(2,'0')}`,range:`${fmt(s).slice(0,5)}–${fmt(e).slice(0,5)}`})}return weeks}
function eventStatus(plan,date){const ex=state.executions.find(e=>e.planUid===plan.uid&&(e.plannedDate===date||e.doneDate===date));if(ex)return'Concluído';const ord=state.orders.find(o=>o.planUid===plan.uid&&o.plannedDate===date&&!['Cancelada'].includes(o.status));if(ord)return ord.status==='Concluída'?'Concluído':'Programado';if(date<today())return'Vencido';if(daysBetween(today(),date)<=14)return'A vencer';return'Planejado'}
function planEvents52(p,weeks){const start=weeks[0].start,end=weeks[weeks.length-1].end,f=Math.max(1,+p.periodicidade||30),events=[];let d=addDays(lastReference(p),f),lastOverdue=null,guard=0;while(d<start&&guard++<2000){if(d<today())lastOverdue=d;d=addDays(d,f)}if(lastOverdue)events.push({date:lastOverdue,status:'Vencido',backlog:true});while(d<=end&&guard++<3000){events.push({date:d,status:eventStatus(p,d)});d=addDays(d,f)}state.orders.filter(o=>o.planUid===p.uid&&o.plannedDate>=start&&o.plannedDate<=end&&!['Cancelada'].includes(o.status)).forEach(o=>{const same=events.find(e=>e.date===o.plannedDate);if(same){same.status=o.status==='Concluída'?'Concluído':'Programado';same.order=o}else events.push({date:o.plannedDate,status:o.status==='Concluída'?'Concluído':'Programado',order:o})});return events.sort((a,b)=>a.date.localeCompare(b.date))}
function statusClass(s){return{'Vencido':'overdue','A vencer':'soon','Programado':'programmed','Planejado':'planned','Concluído':'done'}[s]||'planned'}
function fillMapFilters(){const sectors=[...new Set(state.plans.map(p=>p.setor).filter(Boolean))].sort(),owners=[...new Set(state.plans.map(p=>p.responsavel).filter(Boolean))].sort();const fill=(id,items,label)=>{const el=$(id),cur=el.value;el.innerHTML=`<option value="">${label}</option>`+items.map(x=>`<option ${x===cur?'selected':''}>${esc(x)}</option>`).join('')};fill('#mapSector',sectors,'Todos os setores');fill('#mapOwner',owners,'Todos os responsáveis')}
const expandedMapGroups=new Set();
window.toggleMapGroup=k=>{expandedMapGroups.has(k)?expandedMapGroups.delete(k):expandedMapGroups.add(k);renderMap()};
function aggregateWeekCell(items,weeks,wi){const events=[];items.forEach(p=>planEvents52(p,weeks).filter(e=>!e.backlog&&e.date>=weeks[wi].start&&e.date<=weeks[wi].end).forEach(e=>events.push(e)));if(!events.length)return'';const priority=['Vencido','A vencer','Programado','Planejado','Concluído'];const status=priority.find(s=>events.some(e=>e.status===s))||'Planejado';return `<button class="event-count ${statusClass(status)}" title="${events.length} intervenção(ões) nesta semana">${events.length}</button>`}
function renderTagMapRow(p,weeks){const events=planEvents52(p,weeks),over=events.find(e=>e.backlog),byWeek={};events.filter(e=>!e.backlog).forEach(e=>{const wi=weeks.findIndex(w=>e.date>=w.start&&e.date<=w.end);if(wi>=0)(byWeek[wi]??=[]).push(e)});return `<div class="map-row tag-map-row"><div class="map-fixed"><strong>↳ ${esc(p.tag)} · ${esc(p.descricao||p.plano)}</strong><small>${esc(p.setor||'—')} · ${p.periodicidade} dias · Última: ${fmt(lastReference(p))} · Próxima: ${fmt(dueDate(p))}</small><button class="map-program" onclick="newOrderForPlan('${p.uid}')">+ Programar SS</button></div><div class="map-backlog">${over?`<button class="event-dot overdue" title="Vencido em ${fmt(over.date)}" onclick="openExecute('${p.uid}','${over.date}')">${fmt(over.date).slice(0,5)}</button>`:'—'}</div>${weeks.map(w=>{const es=byWeek[w.i]||[];return `<div class="week-cell">${es.map(e=>`<button class="event-dot ${statusClass(e.status)}" title="${e.status} · ${fmt(e.date)}" onclick="${e.status==='Programado'?`newOrderForPlan('${p.uid}')`:`openExecute('${p.uid}','${e.date}')`}">${fmt(e.date).slice(0,5)}</button>`).join('')}</div>`}).join('')}</div>`}
function renderMap(){const box=$('#maintenanceMap');if(!box)return;fillMapFilters();const weeks=weekList52(),q=$('#mapSearch').value.toLowerCase(),sec=$('#mapSector').value,own=$('#mapOwner').value,sit=$('#mapSituation').value;let plans=state.plans.filter(p=>p.ativo&&(!q||[p.id,p.plano,p.tag,p.descricao].join(' ').toLowerCase().includes(q))&&(!sec||p.setor===sec)&&(!own||p.responsavel===own));if(sit)plans=plans.filter(p=>planEvents52(p,weeks).some(e=>e.status===sit));const groups=planGroups(plans);let counts={Vencido:0,'A vencer':0,Programado:0,Planejado:0,Concluído:0};plans.forEach(p=>planEvents52(p,weeks).forEach(e=>{if(counts[e.status]!=null)counts[e.status]++}));$('#mapSummary').innerHTML=`<span><strong>${groups.length}</strong> planos</span><span><strong>${plans.length}</strong> vínculos plano/TAG</span><span><strong>${new Set(plans.map(p=>p.tag)).size}</strong> TAGs</span><span class="txt-red">${counts.Vencido} vencidos</span><span class="txt-amber">${counts['A vencer']} a vencer</span><span class="txt-blue">${counts.Programado} programados</span>`;
const head=`<div class="map-row map-head"><div class="map-fixed head-fixed">Plano / TAG</div><div class="map-backlog head-fixed">Vencida</div>${weeks.map(w=>`<div class="week-head" data-week="${w.i}"><strong>${w.label}</strong><small>${w.range}</small></div>`).join('')}</div>`;
const rows=groups.map(g=>{const expanded=expandedMapGroups.has(g.key),late=g.items.filter(p=>planEvents52(p,weeks).some(e=>e.backlog)).length,periods=[...g.periods].sort((a,b)=>a-b).join(', ');const groupRow=`<div class="map-row plan-map-row"><div class="map-fixed"><strong><button class="map-expand" onclick='toggleMapGroup(${JSON.stringify(g.key)})'>${expanded?'−':'+'}</button> ${esc(g.name)}</strong><small>${g.tags.size} TAG(s) · periodicidade ${periods} dias · ${late} vencida(s)</small><button class="map-program" onclick='toggleMapGroup(${JSON.stringify(g.key)})'>${expanded?'Ocultar TAGs':'Ver TAGs e datas'}</button></div><div class="map-backlog">${late?`<span class="backlog-count">${late}</span>`:'—'}</div>${weeks.map(w=>`<div class="week-cell">${aggregateWeekCell(g.items,weeks,w.i)}</div>`).join('')}</div>`;const children=expanded?g.items.sort((a,b)=>a.tag.localeCompare(b.tag,'pt-BR')).map(p=>renderTagMapRow(p,weeks)).join(''):'';return groupRow+children}).join('');box.innerHTML=`<div class="map-grid">${head}${rows||'<div class="empty map-empty">Nenhum plano encontrado.</div>'}</div>`}
window.renderMap=renderMap;
$('#btnMapToday').onclick=()=>{const el=$('#maintenanceMap');el.scrollLeft=0};['mapSearch'].forEach(id=>$('#'+id).oninput=renderMap);['mapSector','mapOwner','mapSituation'].forEach(id=>$('#'+id).onchange=renderMap);


const expandedGanttGroups=new Set();
function fillGanttFilters(){
  const sectors=[...new Set(state.plans.map(p=>p.setor).filter(Boolean))].sort();
  const owners=[...new Set(state.plans.map(p=>p.responsavel).filter(Boolean))].sort();
  const fill=(id,items,label)=>{const el=$(id);if(!el)return;const cur=el.value;el.innerHTML=`<option value="">${label}</option>`+items.map(x=>`<option ${x===cur?'selected':''}>${esc(x)}</option>`).join('')};
  fill('#ganttSector',sectors,'Todos os setores');fill('#ganttOwner',owners,'Todos os responsáveis');
}
function ganttPlannedDates(p,weeks){
  const start=weeks[0].start,end=weeks[weeks.length-1].end,dates=new Map();
  // datas planejadas preservadas no histórico
  state.executions.filter(e=>e.planUid===p.uid&&e.plannedDate>=start&&e.plannedDate<=end).forEach(e=>dates.set(e.plannedDate,{date:e.plannedDate,source:'Histórico'}));
  // datas programadas via SS
  state.orders.filter(o=>o.planUid===p.uid&&o.plannedDate>=start&&o.plannedDate<=end&&o.status!=='Cancelada').forEach(o=>dates.set(o.plannedDate,{date:o.plannedDate,source:'SS',programmed:true}));
  // projeção futura pela periodicidade a partir da última referência
  const f=Math.max(1,+p.periodicidade||30);let d=addDays(lastReference(p),f),guard=0;
  while(d<start&&guard++<2000)d=addDays(d,f);
  while(d<=end&&guard++<3000){if(!dates.has(d))dates.set(d,{date:d,source:'Periodicidade'});d=addDays(d,f)}
  // se existe vencida anterior à semana inicial, traz para primeira semana como backlog visual
  const x=latestOverdueAndNext(p,start);if(x.lastOverdue&&x.lastOverdue>=addDays(start,-7))dates.set(x.lastOverdue,{date:x.lastOverdue,source:'Periodicidade'});
  return [...dates.values()].sort((a,b)=>a.date.localeCompare(b.date));
}
function ganttActualDates(p,weeks){const start=weeks[0].start,end=weeks[weeks.length-1].end;return state.executions.filter(e=>e.planUid===p.uid&&e.doneDate&&e.doneDate>=start&&e.doneDate<=end).map(e=>({date:e.doneDate,plannedDate:e.plannedDate||'',ss:e.ss||''})).sort((a,b)=>a.date.localeCompare(b.date))}
function ganttWeekIndex(date,weeks){return weeks.findIndex(w=>date>=w.start&&date<=w.end)}
function ganttMode(){return $('#ganttMode')?.value||'planned'}
function ganttTagCell(p,w,weeks){
  const mode=ganttMode();
  const pl=ganttPlannedDates(p,weeks).filter(e=>e.date>=w.start&&e.date<=w.end), ac=ganttActualDates(p,weeks).filter(e=>e.date>=w.start&&e.date<=w.end);
  const planned=pl.map(e=>{const doneForPlan=state.executions.some(x=>x.planUid===p.uid&&x.plannedDate===e.date);const overdue=e.date<today()&&!doneForPlan;const cls=e.programmed?'programmed':overdue?'overdue':'planned';return `<button class="mini-event ${cls}" title="${e.programmed?'SS programada':'Planejado'} ${fmt(e.date)}${overdue?' · VENCIDO':''}" onclick="openExecute('${p.uid}','${e.date}')">${pl.length>1?pl.length:'1'}</button>`}).join('');
  const actual=ac.map(e=>`<span class="mini-event actual" title="Realizado ${fmt(e.date)}${e.plannedDate?' · planejado '+fmt(e.plannedDate):''}">${ac.length>1?ac.length:'1'}</span>`).join('');
  if(mode==='planned')return planned||'';
  if(mode==='actual')return actual||'';
  if(!planned&&!actual)return '';
  return `<div class="dual-event"><div>${planned}</div><div>${actual}</div></div>`;
}
function ganttAggregateCell(items,w,weeks){
  const mode=ganttMode();let pc=0,rc=0,oc=0,sc=0;
  items.forEach(p=>{const pl=ganttPlannedDates(p,weeks).filter(e=>e.date>=w.start&&e.date<=w.end);pc+=pl.length;sc+=pl.filter(e=>e.programmed).length;pl.forEach(e=>{const done=state.executions.some(x=>x.planUid===p.uid&&x.plannedDate===e.date);if(e.date<today()&&!done)oc++});rc+=ganttActualDates(p,weeks).filter(e=>e.date>=w.start&&e.date<=w.end).length});
  if(mode==='planned'){if(!pc)return '';return `<span class="week-count ${oc?'overdue':sc?'programmed':'planned'}" title="${pc} planejada(s)${oc?' · '+oc+' vencida(s)':''}">${pc}</span>`}
  if(mode==='actual'){if(!rc)return '';return `<span class="week-count actual" title="${rc} realizada(s)">${rc}</span>`}
  if(!pc&&!rc)return '';
  return `<div class="week-pair" title="Planejado ${pc} · Realizado ${rc}">${pc?`<span class="week-count ${oc?'overdue':sc?'programmed':'planned'}">${pc}</span>`:''}${rc?`<span class="week-count actual">${rc}</span>`:''}</div>`;
}
window.toggleGanttGroup=k=>{expandedGanttGroups.has(k)?expandedGanttGroups.delete(k):expandedGanttGroups.add(k);renderGantt()};
function renderGantt(){
  const box=$('#ganttChart');if(!box)return;fillGanttFilters();const weeks=weekList52();
  const q=$('#ganttSearch')?.value.toLowerCase()||'',sec=$('#ganttSector')?.value||'',own=$('#ganttOwner')?.value||'';
  const plans=state.plans.filter(p=>p.ativo&&(!q||[p.id,p.plano,p.tag,p.descricao].join(' ').toLowerCase().includes(q))&&(!sec||p.setor===sec)&&(!own||p.responsavel===own));const groups=planGroups(plans);
  let planned=0,actual=0,overdue=0,onTime=0,duePast=0;
  plans.forEach(p=>{const pls=ganttPlannedDates(p,weeks);planned+=pls.length;actual+=ganttActualDates(p,weeks).length;pls.forEach(e=>{if(e.date<=today()){duePast++;const ex=state.executions.find(x=>x.planUid===p.uid&&x.plannedDate===e.date);if(ex){if(ex.doneDate<=e.date)onTime++}else if(e.date<today())overdue++}})});
  $('#ganttPlanned').textContent=planned;$('#ganttActual').textContent=actual;$('#ganttOverdue').textContent=overdue;$('#ganttCompliance').textContent=duePast?Math.round(onTime/duePast*100)+'%':'—';
  $('#ganttSummary').innerHTML=`<span><strong>${groups.length}</strong> planos</span><span><strong>${new Set(plans.map(p=>p.tag)).size}</strong> TAGs</span>`;
  const head=`<div class="gantt-row gantt-head"><div class="gantt-fixed"><strong>Equipamento / atividade</strong><small>Plano · TAG · periodicidade</small></div>${weeks.map(w=>`<div class="gantt-week-head"><strong>${w.label}</strong><small>${w.range}</small></div>`).join('')}</div>`;
  const rows=groups.map(g=>{const expanded=expandedGanttGroups.has(g.key),periods=[...g.periods].sort((a,b)=>a-b).join(', ');const parent=`<div class="gantt-row gantt-group-row"><div class="gantt-fixed"><button class="row-expand" onclick='toggleGanttGroup(${JSON.stringify(g.key)})'>${expanded?'−':'+'}</button><div><strong>${esc(g.name)}</strong><small>${g.tags.size} TAG(s) · ${periods} dias</small></div></div>${weeks.map(w=>`<div class="gantt-week">${ganttAggregateCell(g.items,w,weeks)}</div>`).join('')}</div>`;const child=expanded?g.items.sort((a,b)=>a.tag.localeCompare(b.tag,'pt-BR')).map(p=>`<div class="gantt-row gantt-tag-row"><div class="gantt-fixed"><div class="tag-indent"></div><div><strong>${esc(p.tag)} · ${esc(p.descricao||p.plano)}</strong><small>Última ${fmt(lastReference(p))} · Próxima ${fmt(dueDate(p))}</small></div></div>${weeks.map(w=>`<div class="gantt-week">${ganttTagCell(p,w,weeks)}</div>`).join('')}</div>`).join(''):'';return parent+child}).join('');
  box.innerHTML=`<div class="gantt-grid">${head}${rows||'<div class="empty">Nenhum plano encontrado.</div>'}</div>`;
}
window.renderGantt=renderGantt;
if($('#ganttSearch'))$('#ganttSearch').oninput=renderGantt;if($('#ganttSector'))$('#ganttSector').onchange=renderGantt;if($('#ganttOwner'))$('#ganttOwner').onchange=renderGantt;if($('#ganttMode'))$('#ganttMode').onchange=renderGantt;
if($('#btnGanttExpand'))$('#btnGanttExpand').onclick=()=>{planGroups(state.plans.filter(p=>p.ativo)).forEach(g=>expandedGanttGroups.add(g.key));renderGantt()};
if($('#btnGanttCollapse'))$('#btnGanttCollapse').onclick=()=>{expandedGanttGroups.clear();renderGantt()};

const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderMap();renderUsers();showLogin()};
showLogin();renderAll();
