const KEY='pcm_preventiva_v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
const today=()=>new Date().toISOString().slice(0,10);
function seedState(){return {plans:clone(window.SEED_PLANS||[]),executions:[],version:1,updatedAt:new Date().toISOString()}}
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.plans) return x}catch(e){} return seedState()}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function uid(){return crypto?.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function fmtDate(s){if(!s)return '—';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`}
function parseDate(s){return new Date(s+'T12:00:00')}
function addDays(s,n){const d=parseDate(s);d.setDate(d.getDate()+Number(n));return d.toISOString().slice(0,10)}
function daysBetween(a,b){return Math.round((parseDate(b)-parseDate(a))/86400000)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function getPlan(u){return state.plans.find(p=>p.uid===u)}
function lastExecution(u){return state.executions.filter(e=>e.planUid===u&&e.closeDate).sort((a,b)=>b.closeDate.localeCompare(a.closeDate))[0]}
function nextDue(p){const last=lastExecution(p.uid);let base=last?.closeDate||p.dataBase||today();let next=base;const freq=Math.max(1,Number(p.periodicidade)||30);while(next<today()) next=addDays(next,freq);return next}
function latestDueAtOrBeforeToday(p){const last=lastExecution(p.uid);let base=last?.closeDate||p.dataBase||today();const freq=Math.max(1,Number(p.periodicidade)||30);let due=base;while(addDays(due,freq)<=today()) due=addDays(due,freq);return due}
function isOverdue(p){if(!p.ativo)return false;const last=lastExecution(p.uid);let due=last?addDays(last.closeDate,p.periodicidade):p.dataBase;if(!due)return false;return due<today()}
function scheduledItems(days=90){const end=addDays(today(),days),out=[];state.plans.filter(p=>p.ativo).forEach(p=>{let d=lastExecution(p.uid)?addDays(lastExecution(p.uid).closeDate,p.periodicidade):(p.dataBase||today());const freq=Math.max(1,Number(p.periodicidade)||30);let guard=0;while(d<today()&&guard++<1000)d=addDays(d,freq);while(d<=end&&guard++<1300){out.push({date:d,plan:p});d=addDays(d,freq)}});return out.sort((a,b)=>a.date.localeCompare(b.date))}
function statusExec(e){if(e.closeDate)return parseDate(e.closeDate)<=parseDate(e.plannedDate)?'Realizado no prazo':'Realizado com atraso';if(e.plannedDate<today())return 'Vencido';if(e.ssOpen==='Sim')return 'SS aberta';return 'Planejado'}

function renderDashboard(){const active=state.plans.filter(p=>p.ativo);$('#kpiActive').textContent=active.length;$('#kpiNext').textContent=scheduledItems(30).length;$('#kpiOverdue').textContent=active.filter(isOverdue).length;const done=state.executions.filter(e=>e.closeDate);const ontime=done.filter(e=>e.closeDate<=e.plannedDate).length;$('#kpiCompliance').textContent=done.length?Math.round(ontime/done.length*100)+'%':'—';
 const list=scheduledItems(30).slice(0,8);$('#nextList').innerHTML=list.length?list.map(x=>`<div class="list-item"><div class="datebox">${fmtDate(x.date)}</div><div><strong>${esc(x.plan.plano)}</strong><small>${esc(x.plan.tag)} · ${esc(x.plan.setor)}</small></div><span class="badge">${x.plan.periodicidade} dias</span></div>`).join(''):'<div class="empty">Nenhuma preventiva nos próximos 30 dias.</div>';
 const counts={};active.forEach(p=>counts[p.setor||'Sem setor']=(counts[p.setor||'Sem setor']||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);const max=Math.max(1,...top.map(x=>x[1]));$('#sectorBars').innerHTML=top.map(([k,v])=>`<div class="bar-row"><span title="${esc(k)}">${esc(k.slice(0,18))}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><strong>${v}</strong></div>`).join('');
 const cr=['Crítica','Alta','Média','Baixa'];$('#criticalitySummary').innerHTML=cr.map(c=>`<span class="chip"><strong>${active.filter(p=>p.criticidade===c).length}</strong> ${c}</span>`).join('')}
function renderFilters(){const cur=$('#sectorFilter').value;const sectors=[...new Set(state.plans.map(p=>p.setor).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('#sectorFilter').innerHTML='<option value="">Todos os setores</option>'+sectors.map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('');$('#seedCount').textContent=`${state.plans.length} planos/TAGs`}
function renderPlans(){const q=$('#planSearch').value.toLowerCase(),sec=$('#sectorFilter').value,st=$('#statusFilter').value;const rows=state.plans.filter(p=>(!q||[p.id,p.plano,p.tag,p.descricao,p.responsavel].join(' ').toLowerCase().includes(q))&&(!sec||p.setor===sec)&&(st===''||String(!!p.ativo)===st));$('#plansBody').innerHTML=rows.length?rows.map(p=>`<tr><td><strong>${esc(p.id)}</strong></td><td>${esc(p.plano)}</td><td>${esc(p.tag)}</td><td>${esc(p.descricao)}</td><td>${esc(p.setor)}</td><td>${esc(p.periodicidade)} dias</td><td>${esc(p.responsavel||'—')}</td><td><span class="badge ${p.criticidade==='Crítica'?'critical':''}">${esc(p.criticidade)}</span></td><td><span class="badge ${p.ativo?'':'gray'}">${p.ativo?'Ativo':'Inativo'}</span></td><td><div class="actions"><button class="mini" onclick="openExec('${p.uid}','${nextDue(p)}')" title="Registrar execução">✓</button><button class="mini" onclick="editPlan('${p.uid}')" title="Editar">✎</button><button class="mini" onclick="removePlan('${p.uid}')" title="Excluir">⌫</button></div></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nenhum plano encontrado.</td></tr>'}
function renderAgenda(){const days=Number($('#agendaDays').value),q=$('#agendaSearch').value.toLowerCase();let rows=scheduledItems(days).filter(x=>!q||[x.plan.id,x.plan.plano,x.plan.tag,x.plan.setor].join(' ').toLowerCase().includes(q));$('#agendaBody').innerHTML=rows.length?rows.map(x=>{const overdue=x.date<today();return `<tr><td><strong>${fmtDate(x.date)}</strong></td><td><span class="badge ${overdue?'red':'amber'}">${overdue?'Vencido':'Planejado'}</span></td><td>${esc(x.plan.id)}</td><td>${esc(x.plan.plano)}</td><td>${esc(x.plan.tag)}</td><td>${esc(x.plan.setor)}</td><td>${x.plan.periodicidade} dias</td><td>${esc(x.plan.responsavel||'—')}</td><td><button class="mini" onclick="openExec('${x.plan.uid}','${x.date}')">Registrar</button></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma programação encontrada.</td></tr>'}
function renderExecutions(){const q=$('#executionSearch').value.toLowerCase();const rows=[...state.executions].sort((a,b)=>b.plannedDate.localeCompare(a.plannedDate)).filter(e=>{const p=getPlan(e.planUid)||{};return !q||[p.plano,p.tag,e.ssNumber,e.owner,e.notes].join(' ').toLowerCase().includes(q)});$('#executionBody').innerHTML=rows.length?rows.map(e=>{const p=getPlan(e.planUid)||{};const st=statusExec(e);return `<tr><td>${fmtDate(e.plannedDate)}</td><td>${fmtDate(e.closeDate)}</td><td>${esc(p.plano||'Plano removido')}</td><td>${esc(p.tag||'—')}</td><td>${esc(e.ssNumber||'—')}</td><td>${esc(e.owner||'—')}</td><td><span class="badge ${st==='Vencido'?'red':st.includes('atraso')?'amber':''}">${st}</span></td><td>${esc(e.notes||'—')}</td><td><button class="mini" onclick="removeExecution('${e.uid}')">⌫</button></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma execução registrada ainda.</td></tr>'}
function renderAll(){renderFilters();renderDashboard();renderPlans();renderAgenda();renderExecutions()}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent={dashboard:'Dashboard',planos:'Planos de manutenção',agenda:'Agenda preventiva',execucoes:'Execuções / SS',backup:'Backup e restauração'}[id];$('#btnNew').style.display=id==='backup'?'none':''}
function openPlan(p=null){$('#planForm').reset();$('#uid').value=p?.uid||'';$('#planId').value=p?.id||nextPlanId();$('#tag').value=p?.tag||'';$('#planName').value=p?.plano||'';$('#description').value=p?.descricao||'';$('#sector').value=p?.setor||'';$('#owner').value=p?.responsavel||'';$('#frequency').value=p?.periodicidade||30;$('#baseDate').value=p?.dataBase||today();$('#criticality').value=p?.criticidade||'Média';$('#active').checked=p?!!p.ativo:true;$('#planModalTitle').textContent=p?'Editar plano preventivo':'Novo plano preventivo';$('#planDialog').showModal()}
function nextPlanId(){const nums=state.plans.map(p=>Number(String(p.id).match(/\d+/)?.[0]||0));return 'PLN-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
window.editPlan=u=>openPlan(getPlan(u));
window.removePlan=u=>{const p=getPlan(u);if(!p)return;if(confirm(`Excluir o plano ${p.id} / ${p.tag}? O histórico de execuções será mantido.`)){state.plans=state.plans.filter(x=>x.uid!==u);save();toast('Plano excluído')}};
window.openExec=(u,date)=>{const p=getPlan(u);if(!p)return;$('#executionForm').reset();$('#execPlanUid').value=u;$('#plannedDate').value=date||nextDue(p);$('#execOwner').value=p.responsavel||'';$('#selectedPlanInfo').innerHTML=`<strong>${esc(p.id)} · ${esc(p.plano)}</strong><br>${esc(p.tag)} · ${esc(p.descricao)} · periodicidade ${p.periodicidade} dias`;$('#executionDialog').showModal()};
window.removeExecution=u=>{if(confirm('Excluir este registro de execução?')){state.executions=state.executions.filter(e=>e.uid!==u);save();toast('Execução excluída')}};
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pcm-preventiva-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}

$('#planForm').addEventListener('submit',e=>{e.preventDefault();const data={uid:$('#uid').value||uid(),id:$('#planId').value.trim(),plano:$('#planName').value.trim(),tag:$('#tag').value.trim(),descricao:$('#description').value.trim(),setor:$('#sector').value.trim(),periodicidade:Number($('#frequency').value),responsavel:$('#owner').value.trim(),dataBase:$('#baseDate').value,criticidade:$('#criticality').value,ativo:$('#active').checked};const i=state.plans.findIndex(p=>p.uid===data.uid);if(i>=0)state.plans[i]=data;else state.plans.unshift(data);$('#planDialog').close();save();toast(i>=0?'Plano atualizado':'Plano cadastrado')});
$('#executionForm').addEventListener('submit',e=>{e.preventDefault();state.executions.push({uid:uid(),planUid:$('#execPlanUid').value,plannedDate:$('#plannedDate').value,ssOpen:$('#ssOpen').value,ssNumber:$('#ssNumber').value.trim(),openDate:$('#openDate').value,closeDate:$('#closeDate').value,owner:$('#execOwner').value.trim(),notes:$('#notes').value.trim(),createdAt:new Date().toISOString()});$('#executionDialog').close();save();toast('Execução registrada')});
$$('.close-dialog').forEach(b=>b.onclick=()=>$('#planDialog').close());$$('.close-exec').forEach(b=>b.onclick=()=>$('#executionDialog').close());$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>switchView(b.dataset.goto));$('#btnNew').onclick=()=>openPlan();$('#btnExport').onclick=exportBackup;$('#backupExport').onclick=exportBackup;$('#planSearch').oninput=renderPlans;$('#sectorFilter').onchange=renderPlans;$('#statusFilter').onchange=renderPlans;$('#agendaDays').onchange=renderAgenda;$('#agendaSearch').oninput=renderAgenda;$('#executionSearch').oninput=renderExecutions;
$('#backupImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.plans)||!Array.isArray(data.executions))throw Error();if(confirm('Importar este backup e substituir os dados atuais?')){state=data;save();toast('Backup restaurado')}}catch{alert('Arquivo de backup inválido.')}e.target.value=''};
$('#resetData').onclick=()=>{if(confirm('Restaurar a base original? Todas as alterações e execuções locais serão apagadas.')){state=seedState();save();toast('Base original restaurada')}};
renderAll();
