const KEY='pcm_preventiva_v2';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const clone=o=>JSON.parse(JSON.stringify(o));
const today=()=>new Date().toISOString().slice(0,10);const fmt=s=>{if(!s)return'—';const [y,m,d]=s.split('-');return`${d}/${m}/${y}`};const parse=s=>new Date(s+'T12:00:00');const addDays=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+Number(n));return d.toISOString().slice(0,10)};const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const uid=()=>crypto?.randomUUID?.()||'id-'+Date.now()+Math.random();
function normalizePlan(p){return{...p,disciplina:p.disciplina||guessDiscipline(p.plano,p.descricao),duracaoEstimada:Number(p.duracaoEstimada||1),equipe:Number(p.equipe||1),materiais:p.materiais||'',checklist:Array.isArray(p.checklist)?p.checklist:defaultChecklist(p),criticidade:p.criticidade||'Média',ativo:p.ativo!==false}}
function guessDiscipline(a='',b=''){const t=(a+' '+b).toLowerCase();if(/el[eé]tric|motor|painel|sensor|cabo/.test(t))return'Elétrica';if(/lubri|graxa|óleo|oleo/.test(t))return'Lubrificação';if(/clp|autom|i\/o|software|inversor/.test(t))return'Automação';return'Mecânica'}
function defaultChecklist(p){const n=(p.plano||'').toLowerCase();if(/lubri/.test(n))return['Verificar condição e ponto de lubrificação','Limpar ponto antes da aplicação','Aplicar lubrificante conforme especificação','Registrar anomalias'];return['Inspecionar condição geral do equipamento','Verificar fixações, folgas e ruídos anormais','Verificar componentes de desgaste','Limpar área de intervenção','Registrar anomalias encontradas']}
function seedState(){return{version:2,plans:clone(window.SEED_PLANS||[]).map(normalizePlan),orders:[],executions:[],updatedAt:new Date().toISOString()}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d?.plans)return migrate(d)}catch{}return seedState()}
function migrate(d){d.version=2;d.plans=(d.plans||[]).map(normalizePlan);d.orders=d.orders||[];d.executions=d.executions||[];return d}let state=load();
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}function getPlan(u){return state.plans.find(p=>p.uid===u)}
function lastDone(u){return state.executions.filter(e=>e.planUid===u&&e.doneDate).sort((a,b)=>b.doneDate.localeCompare(a.doneDate))[0]}
function dueDate(p){const l=lastDone(p.uid);return l?addDays(l.doneDate,p.periodicidade):p.dataBase||today()}
function isLate(p){return p.ativo&&dueDate(p)<today()}
function schedule(days=90){const end=addDays(today(),days),rows=[];state.plans.filter(p=>p.ativo).forEach(p=>{let d=dueDate(p),f=Math.max(1,+p.periodicidade||30),g=0;while(d<today()&&g++<1000){rows.push({date:d,plan:p,late:true});d=addDays(d,f)}while(d<=end&&g++<1300){rows.push({date:d,plan:p,late:false});d=addDays(d,f)}});return rows.sort((a,b)=>a.date.localeCompare(b.date))}
function assetList(){const m=new Map();state.plans.forEach(p=>{if(!m.has(p.tag))m.set(p.tag,{tag:p.tag,descricao:p.descricao,setor:p.setor,plans:[]});m.get(p.tag).plans.push(p)});return[...m.values()]}
const critRank={Crítica:4,Alta:3,Média:2,Baixa:1};function worstCrit(plans){return[...plans].sort((a,b)=>(critRank[b.criticidade]||0)-(critRank[a.criticidade]||0))[0]?.criticidade||'—'}
function nextPlanId(){const n=state.plans.map(p=>+(String(p.id).match(/\d+/)?.[0]||0));return'PLN-'+String(Math.max(0,...n)+1).padStart(3,'0')}function nextOrder(){const n=state.orders.map(o=>+(String(o.number).match(/\d+/)?.[0]||0));return'SS-'+String(Math.max(0,...n)+1).padStart(5,'0')}
function badge(v){let c='';if(['Vencido','Crítica'].includes(v))c='red';else if(['Alta','Aguardando material'].includes(v))c='amber';else if(['Em execução'].includes(v))c='blue';else if(['Cancelada','Inativo'].includes(v))c='gray';return`<span class="badge ${c}">${esc(v)}</span>`}
function renderDashboard(){const active=state.plans.filter(p=>p.ativo),assets=assetList(),sch=schedule(30),late=active.filter(isLate),open=state.orders.filter(o=>!['Concluída','Cancelada'].includes(o.status)),done=state.executions.filter(e=>e.doneDate),ontime=done.filter(e=>e.doneDate<=e.plannedDate);$('#kpiPlans').textContent=active.length;$('#kpiAssets').textContent=assets.length;$('#kpi30').textContent=sch.filter(x=>!x.late).length;$('#kpiLate').textContent=late.length;$('#kpiOpenOrders').textContent=open.length;$('#kpiCompliance').textContent=done.length?Math.round(ontime.length/done.length*100)+'%':'—';
const upcoming=schedule(30).slice(0,10);$('#upcomingList').innerHTML=upcoming.length?upcoming.map(x=>`<div class="timeline-item"><div class="datebox">${fmt(x.date)}</div><div><strong>${esc(x.plan.plano)}</strong><small>${esc(x.plan.tag)} · ${esc(x.plan.setor)} · ${esc(x.plan.responsavel||'Sem responsável')}</small></div>${badge(x.late?'Vencido':x.plan.criticidade)}</div>`).join(''):'<div class="empty">Sem programação.</div>';
const pc={Crítica:0,Alta:0,Média:0,Baixa:0};late.forEach(p=>pc[p.criticidade]=(pc[p.criticidade]||0)+1);$('#priorityDonut').innerHTML=Object.entries(pc).map(([k,v])=>`<div class="priority-card"><span>${k}</span><strong>${v}</strong></div>`).join('');
const counts={};active.forEach(p=>counts[p.setor||'Sem setor']=(counts[p.setor||'Sem setor']||0)+1);renderBars('#sectorBars',counts);
const alerts=[];if(late.length)alerts.push(`<div class="alert"><strong>${late.length} preventiva(s) vencida(s)</strong><small>Priorize a regularização do backlog.</small></div>`);if(open.filter(o=>o.status==='Aguardando material').length)alerts.push(`<div class="alert"><strong>${open.filter(o=>o.status==='Aguardando material').length} SS aguardando material</strong><small>Verifique compras e disponibilidade de peças.</small></div>`);const criticalLate=late.filter(p=>p.criticidade==='Crítica').length;if(criticalLate)alerts.push(`<div class="alert"><strong>${criticalLate} plano(s) crítico(s) vencido(s)</strong><small>Requer ação prioritária.</small></div>`);if(!alerts.length)alerts.push('<div class="alert"><strong>Sem alertas críticos</strong><small>A programação está sob controle.</small></div>');$('#alerts').innerHTML=alerts.join('')}
function renderBars(sel,obj){const arr=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,12),mx=Math.max(1,...arr.map(x=>x[1]));$(sel).innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-row"><span title="${esc(k)}">${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/mx*100}%"></div></div><strong>${v}</strong></div>`).join(''):'<div class="empty">Sem dados.</div>'}
function fillSectors(){const sectors=[...new Set(state.plans.map(p=>p.setor).filter(Boolean))].sort();for(const id of ['assetSector','planSector']){const el=$(id.startsWith('#')?id:'#'+id),cur=el.value;el.innerHTML='<option value="">Todos os setores</option>'+sectors.map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}}
function renderAssets(){const q=$('#assetSearch').value.toLowerCase(),sec=$('#assetSector').value;const rows=assetList().filter(a=>(!q||[a.tag,a.descricao,a.setor].join(' ').toLowerCase().includes(q))&&(!sec||a.setor===sec));$('#assetsBody').innerHTML=rows.length?rows.map(a=>{const act=a.plans.filter(p=>p.ativo);const next=act.map(p=>({p,d:dueDate(p)})).sort((x,y)=>x.d.localeCompare(y.d))[0];return`<tr><td><strong>${esc(a.tag)}</strong></td><td>${esc(a.descricao||'—')}</td><td>${esc(a.setor||'—')}</td><td>${a.plans.length}</td><td>${badge(worstCrit(a.plans))}</td><td>${next?fmt(next.d):'—'}</td><td>${next?badge(next.d<today()?'Vencido':'Em dia'):'—'}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Nenhum equipamento encontrado.</td></tr>'}
function renderPlans(){const q=$('#planSearch').value.toLowerCase(),sec=$('#planSector').value,cr=$('#planCriticality').value,st=$('#planStatus').value;const rows=state.plans.filter(p=>(!q||[p.id,p.plano,p.tag,p.descricao,p.setor,p.responsavel].join(' ').toLowerCase().includes(q))&&(!sec||p.setor===sec)&&(!cr||p.criticidade===cr)&&(st===''||String(!!p.ativo)===st));$('#plansBody').innerHTML=rows.length?rows.map(p=>`<tr><td><strong>${esc(p.id)}</strong></td><td>${esc(p.plano)}</td><td>${esc(p.tag)}</td><td>${esc(p.setor)}</td><td>${esc(p.disciplina)}</td><td>${p.periodicidade} dias</td><td>${esc(p.responsavel||'—')}</td><td>${badge(p.criticidade)}</td><td>${fmt(dueDate(p))}</td><td><div class="actions"><button class="mini" onclick="openExecute('${p.uid}','${dueDate(p)}')">Baixar</button><button class="mini" onclick="editPlan('${p.uid}')">Editar</button><button class="mini" onclick="newOrderForPlan('${p.uid}')">SS</button></div></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nenhum plano encontrado.</td></tr>'}
function renderAgenda(){const q=$('#agendaSearch').value.toLowerCase(),sit=$('#agendaSituation').value,days=+$(`#agendaDays`).value;const rows=schedule(days).filter(x=>!q||[x.plan.id,x.plan.plano,x.plan.tag,x.plan.setor].join(' ').toLowerCase().includes(q)).filter(x=>!sit||(x.late?'Vencido':'Planejado')===sit);$('#agendaBody').innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${fmt(x.date)}</strong></td><td>${badge(x.late?'Vencido':'Planejado')}</td><td>${esc(x.plan.id)}</td><td>${esc(x.plan.plano)}</td><td>${esc(x.plan.tag)}</td><td>${esc(x.plan.setor)}</td><td>${badge(x.plan.criticidade)}</td><td>${esc(x.plan.responsavel||'—')}</td><td><button class="mini" onclick="openExecute('${x.plan.uid}','${x.date}')">Executar</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">Nenhuma atividade encontrada.</td></tr>'}
function renderOrders(){const q=$('#orderSearch').value.toLowerCase(),st=$('#orderStatus').value;const rows=[...state.orders].sort((a,b)=>b.openDate.localeCompare(a.openDate)).filter(o=>(!q||[o.number,o.description,o.tag,o.owner,getPlan(o.planUid)?.plano].join(' ').toLowerCase().includes(q))&&(!st||o.status===st));$('#ordersBody').innerHTML=rows.length?rows.map(o=>{const p=getPlan(o.planUid);return`<tr><td><strong>${esc(o.number)}</strong></td><td>${esc(p?.plano||o.description||'Serviço avulso')}</td><td>${esc(o.tag||p?.tag||'—')}</td><td>${fmt(o.openDate)}</td><td>${fmt(o.plannedDate)}</td><td>${badge(o.priority)}</td><td>${esc(o.owner||'—')}</td><td>${badge(o.status)}</td><td><div class="actions"><button class="mini" onclick="editOrder('${o.uid}')">Editar</button>${o.status!=='Concluída'?`<button class="mini" onclick="executeOrder('${o.uid}')">Baixar</button>`:''}</div></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma SS / ordem cadastrada.</td></tr>'}
function renderHistory(){const q=$('#historySearch').value.toLowerCase(),y=$('#historyYear').value;const rows=[...state.executions].sort((a,b)=>b.doneDate.localeCompare(a.doneDate)).filter(e=>{const p=getPlan(e.planUid)||{};return(!q||[p.plano,p.tag,e.orderNumber,e.owner,e.notes].join(' ').toLowerCase().includes(q))&&(!y||e.doneDate?.startsWith(y))});$('#historyBody').innerHTML=rows.length?rows.map(e=>{const p=getPlan(e.planUid)||{};return`<tr><td>${fmt(e.plannedDate)}</td><td>${fmt(e.doneDate)}</td><td>${esc(p.plano||'Plano removido')}</td><td>${esc(p.tag||'—')}</td><td>${esc(e.orderNumber||'—')}</td><td>${esc(e.owner||'—')}</td><td>${e.hours||0} h</td><td>${badge(e.result||'Concluído')}</td><td>${esc(e.notes||'—')}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Nenhuma execução registrada.</td></tr>';const yrs=[...new Set(state.executions.map(e=>e.doneDate?.slice(0,4)).filter(Boolean))].sort().reverse(),cur=$('#historyYear').value;$('#historyYear').innerHTML='<option value="">Todos os anos</option>'+yrs.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}
function renderIndicators(){const done=state.executions.filter(e=>e.doneDate),ont=done.filter(e=>e.doneDate<=e.plannedDate),late=done.filter(e=>e.doneDate>e.plannedDate),hours=done.reduce((s,e)=>s+(+e.hours||0),0);$('#indDone').textContent=done.length;$('#indOntime').textContent=ont.length;$('#indLate').textContent=late.length;$('#indHours').textContent=hours.toFixed(1)+'h';const sectors={};done.forEach(e=>{const p=getPlan(e.planUid),s=p?.setor||'Sem setor';sectors[s]??={t:0,o:0};sectors[s].t++;if(e.doneDate<=e.plannedDate)sectors[s].o++});const rates={};Object.entries(sectors).forEach(([k,v])=>rates[k]=Math.round(v.o/v.t*100));renderBars('#complianceBars',rates);const months=[];let d=new Date();for(let i=11;i>=0;i--){const x=new Date(d.getFullYear(),d.getMonth()-i,1),key=x.toISOString().slice(0,7),lab=String(x.getMonth()+1).padStart(2,'0')+'/'+String(x.getFullYear()).slice(2);months.push({key,lab,v:done.filter(e=>e.doneDate?.startsWith(key)).length})}const mx=Math.max(1,...months.map(m=>m.v));$('#monthBars').innerHTML=months.map(m=>`<div class="month-col"><strong>${m.v}</strong><div class="col" style="height:${Math.max(3,m.v/mx*180)}px"></div><small>${m.lab}</small></div>`).join('');const adh=done.length?Math.round(ont.length/done.length*100):0,avg=done.length?hours/done.length:0;$('#managementSummary').innerHTML=`<div class="summary-item"><span>Aderência global</span><strong>${adh}%</strong></div><div class="summary-item"><span>Duração média</span><strong>${avg.toFixed(1)} h</strong></div><div class="summary-item"><span>Backlog vencido</span><strong>${state.plans.filter(isLate).length}</strong></div><div class="summary-item"><span>Ordens abertas</span><strong>${state.orders.filter(o=>!['Concluída','Cancelada'].includes(o.status)).length}</strong></div>`}
function renderAll(){fillSectors();$('#baseCount').textContent=`${state.plans.length} planos`;renderDashboard();renderAssets();renderPlans();renderAgenda();renderOrders();renderHistory();renderIndicators();fillOrderPlans()}
const titles={dashboard:['Dashboard','Visão geral da programação preventiva'],equipamentos:['Equipamentos','TAGs e cobertura dos planos'],planos:['Planos de manutenção','Cadastro técnico e periodicidades'],agenda:['Programação preventiva','Calendário e backlog das atividades'],ordens:['SS / Ordens','Controle de serviços e andamento'],execucoes:['Histórico de execuções','Rastreabilidade das manutenções realizadas'],indicadores:['Indicadores','Aderência, backlog e esforço preventivo'],backup:['Dados / Backup','Exportação, importação e configurações']};function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1]}
function openPlan(p){$('#planForm').reset();$('#pUid').value=p?.uid||'';$('#pId').value=p?.id||nextPlanId();$('#pTag').value=p?.tag||'';$('#pName').value=p?.plano||'';$('#pDescription').value=p?.descricao||'';$('#pSector').value=p?.setor||'';$('#pOwner').value=p?.responsavel||'';$('#pDiscipline').value=p?.disciplina||'Mecânica';$('#pCriticality').value=p?.criticidade||'Média';$('#pFrequency').value=p?.periodicidade||30;$('#pBaseDate').value=p?.dataBase||today();$('#pDuration').value=p?.duracaoEstimada||1;$('#pCrew').value=p?.equipe||1;$('#pMaterials').value=p?.materiais||'';$('#pChecklist').value=(p?.checklist||[]).join('\n');$('#pActive').checked=p?p.ativo!==false:true;$('#planDialogTitle').textContent=p?'Editar plano':'Novo plano';$('#planDialog').showModal()}window.editPlan=u=>openPlan(getPlan(u));
function fillOrderPlans(){const cur=$('#oPlan').value;$('#oPlan').innerHTML='<option value="">Serviço avulso</option>'+state.plans.map(p=>`<option value="${p.uid}" ${p.uid===cur?'selected':''}>${esc(p.id)} · ${esc(p.tag)} · ${esc(p.plano)}</option>`).join('')}
function openOrder(o,planUid){$('#orderForm').reset();fillOrderPlans();$('#oUid').value=o?.uid||'';$('#oNumber').value=o?.number||nextOrder();$('#oPlan').value=o?.planUid||planUid||'';const p=getPlan($('#oPlan').value);$('#oTag').value=o?.tag||p?.tag||'';$('#oStatus').value=o?.status||'Aberta';$('#oOpenDate').value=o?.openDate||today();$('#oPlannedDate').value=o?.plannedDate||p?dueDate(p):today();$('#oPriority').value=o?.priority||p?.criticidade||'Média';$('#oOwner').value=o?.owner||p?.responsavel||'';$('#oDescription').value=o?.description||p?.plano||'';$('#oNotes').value=o?.notes||'';$('#orderDialogTitle').textContent=o?'Editar SS / Ordem':'Nova SS / Ordem';$('#orderDialog').showModal()}window.editOrder=u=>openOrder(state.orders.find(o=>o.uid===u));window.newOrderForPlan=u=>openOrder(null,u);
function openExecute(planUid,plannedDate,orderUid=''){const p=getPlan(planUid),o=state.orders.find(x=>x.uid===orderUid);if(!p&&o?.planUid)planUid=o.planUid;const pl=getPlan(planUid);if(!pl){alert('É necessário vincular a ordem a um plano para baixar nesta tela.');return}$('#executeForm').reset();$('#ePlanUid').value=pl.uid;$('#eOrderUid').value=orderUid||'';$('#ePlannedDate').value=plannedDate||o?.plannedDate||dueDate(pl);$('#eDoneDate').value=today();$('#eOrderNumber').value=o?.number||'';$('#eOwner').value=o?.owner||pl.responsavel||'';$('#eHours').value=pl.duracaoEstimada||1;$('#execPlanInfo').innerHTML=`<strong>${esc(pl.id)} · ${esc(pl.plano)}</strong><br>${esc(pl.tag)} · ${esc(pl.setor)} · ${pl.periodicidade} dias`;$('#execChecklist').innerHTML=(pl.checklist||[]).map((c,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"> <span>${esc(c)}</span></label>`).join('');$('#executeDialog').showModal()}window.openExecute=openExecute;window.executeOrder=u=>{const o=state.orders.find(x=>x.uid===u);if(!o)return;openExecute(o.planUid,o.plannedDate,o.uid)};
$('#planForm').onsubmit=e=>{e.preventDefault();const d=normalizePlan({uid:$('#pUid').value||uid(),id:$('#pId').value.trim(),tag:$('#pTag').value.trim(),plano:$('#pName').value.trim(),descricao:$('#pDescription').value.trim(),setor:$('#pSector').value.trim(),responsavel:$('#pOwner').value.trim(),disciplina:$('#pDiscipline').value,criticidade:$('#pCriticality').value,periodicidade:+$('#pFrequency').value,dataBase:$('#pBaseDate').value,duracaoEstimada:+$('#pDuration').value,equipe:+$('#pCrew').value,materiais:$('#pMaterials').value.trim(),checklist:$('#pChecklist').value.split('\n').map(x=>x.trim()).filter(Boolean),ativo:$('#pActive').checked});const i=state.plans.findIndex(p=>p.uid===d.uid);if(i>=0)state.plans[i]=d;else state.plans.unshift(d);$('#planDialog').close();save();toast(i>=0?'Plano atualizado':'Plano cadastrado')};
$('#orderForm').onsubmit=e=>{e.preventDefault();const d={uid:$('#oUid').value||uid(),number:$('#oNumber').value.trim(),planUid:$('#oPlan').value,tag:$('#oTag').value.trim(),status:$('#oStatus').value,openDate:$('#oOpenDate').value,plannedDate:$('#oPlannedDate').value,priority:$('#oPriority').value,owner:$('#oOwner').value.trim(),description:$('#oDescription').value.trim(),notes:$('#oNotes').value.trim(),updatedAt:new Date().toISOString()};const i=state.orders.findIndex(o=>o.uid===d.uid);if(i>=0)state.orders[i]=d;else state.orders.unshift(d);$('#orderDialog').close();save();toast(i>=0?'SS atualizada':'SS cadastrada')};
$('#executeForm').onsubmit=e=>{e.preventDefault();const checked=[...document.querySelectorAll('[data-check]')].map((x,i)=>({index:i,done:x.checked}));const ex={uid:uid(),planUid:$('#ePlanUid').value,orderUid:$('#eOrderUid').value,plannedDate:$('#ePlannedDate').value,doneDate:$('#eDoneDate').value,orderNumber:$('#eOrderNumber').value.trim(),owner:$('#eOwner').value.trim(),hours:+$('#eHours').value,result:$('#eResult').value,materials:$('#eMaterials').value.trim(),notes:$('#eNotes').value.trim(),checklist:checked,createdAt:new Date().toISOString()};state.executions.push(ex);if(ex.orderUid){const o=state.orders.find(o=>o.uid===ex.orderUid);if(o)o.status='Concluída'}$('#executeDialog').close();save();toast('Execução registrada')};
$('#oPlan').onchange=()=>{const p=getPlan($('#oPlan').value);if(p){$('#oTag').value=p.tag;$('#oPlannedDate').value=dueDate(p);$('#oPriority').value=p.criticidade;$('#oOwner').value=p.responsavel||'';$('#oDescription').value=p.plano}};
function exportJson(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`pcm-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}function exportCsv(){const cols=['ID','Plano','TAG','Descrição','Setor','Disciplina','Periodicidade','Responsável','Criticidade','Data-base','Ativo'];const lines=[cols.join(';'),...state.plans.map(p=>[p.id,p.plano,p.tag,p.descricao,p.setor,p.disciplina,p.periodicidade,p.responsavel,p.criticidade,p.dataBase,p.ativo?'Sim':'Não'].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';'))];const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`planos-preventiva-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>switchView(b.dataset.goto));$('#btnNewPlan').onclick=()=>openPlan();$('#btnQuickOrder').onclick=()=>openOrder();$('#btnNewOrder2').onclick=()=>openOrder();$$('.close-plan').forEach(b=>b.onclick=()=>$('#planDialog').close());$$('.close-order').forEach(b=>b.onclick=()=>$('#orderDialog').close());$$('.close-exec').forEach(b=>b.onclick=()=>$('#executeDialog').close());
['assetSearch','planSearch','agendaSearch','orderSearch','historySearch'].forEach(id=>$('#'+id).oninput=renderAll);['assetSector','planSector','planCriticality','planStatus','agendaDays','agendaSituation','orderStatus','historyYear'].forEach(id=>$('#'+id).onchange=renderAll);$('#exportJson').onclick=exportJson;$('#exportCsv').onclick=exportCsv;$('#importJson').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.plans))throw 0;if(confirm('Substituir a base atual por este backup?')){state=migrate(d);save();toast('Backup importado')}}catch{alert('Arquivo inválido.')}e.target.value=''};$('#resetData').onclick=()=>{if(confirm('Restaurar a base original e apagar alterações locais?')){state=seedState();save();toast('Base restaurada')}};renderAll();
